name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt update && sudo apt install libfontconfig1-dev

    - name: Check Formatting
      run: cargo fmt --all -- --check
      working-directory: algebraeon

  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt update && sudo apt install libfontconfig1-dev

    - name: Run Code Debug Checks
      run: cargo check --all-targets --all-features
      working-directory: algebraeon
      env:
        RUSTFLAGS: "-D warnings"

    - name: Run Code Release Checks
      run: cargo check --all-targets --all-features --release
      working-directory: algebraeon
      env:
        RUSTFLAGS: "-D warnings"

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt update && sudo apt install libfontconfig1-dev

    - name: Install Clippy
      run: rustup component add clippy

    - name: Run Clippy Checks
      run: cargo clippy -- -D warnings
      working-directory: algebraeon

  test_debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt update && sudo apt install libfontconfig1-dev

    - name: Setup Python venv
      run: |
        python3 -m venv .env
        source .env/bin/activate
        pip install maturin
      working-directory: algebraeon

    - name: Run tests in debug
      run: cargo run
      working-directory: examples

  test_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: sudo apt update && sudo apt install libfontconfig1-dev

    - name: Setup Python venv
      run: |
        python3 -m venv .env
        source .env/bin/activate
        pip install maturin
      working-directory: algebraeon

    - name: Run tests in release
      run: cargo run -- --release
      working-directory: examples
